// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/Example.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/Example.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
